### ISSUE TITLE
Qui dit quoi? ORAL

### ISSUE THREAD

**Issue by Clocloh** [Clocloh/tour_de_france#3]
Qui dit quoi

**Aicha**:
Nom du projet
Contexte
Persona
Logotype
Declinaison logo

**Nous 2:** 
Pb
Recherche logo
Inspiration graphique
Proposition techniques
Prochaines etapes
Retroplanning

**Chloé:**
Benchmark
Concept
Scenario utilisateur
Moodboard
Couleur
Typographie

**Comment by Aysha-P8** [comment]
**En réalité c'est plutôt cette distribution :** 

Aicha:
1 - Présentation projet 
2 - Nom du projet
3 - Contexte
6 – Persona
10 - Inspiration graphique
11 – Recherche logo 
12 – Logotype
13 – Déclinaison logo 

Nous 2 :
16 - Proposition techniques
17 - Prochaines étapes
18 - Retroplanning

Chloé:
4 – Benchmark
5 – Problématique 
7 - Concept
8 - Scenario utilisateur
9 - Moodboard
14 -Couleur 
15 - Typographie
